default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

with_username_and_password: &with_username_and_password
  host:     <%= ENV["DATABASE_HOST"] || "localhost" %>
  username: <%= ENV["DB_USERNAME"] || ENV["DATABASE_USER"] || "dev"  %>
  password: <%= ENV["DB_PASSWORD"] || ENV["DATABASE_PASSWORD"] || "dev"  %>

development:
  <<: *default
  <<: *with_username_and_password
  database: mnu_bragado_development

test:
  <<: *default
  <<: *with_username_and_password
  database: mnu_bragado_test

production:
  <<: *default
  <<: *with_username_and_password
  database: <%= ENV["DB_DATABASE"] || ENV["DATABASE_NAME"] || "mnubragado_production" %>
